# Generated by Django 5.0.2 on 2024-02-28 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskupdate',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskupdate',
            name='user',
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Task Name', max_length=100)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('Started', 'Started'), ('Ongoing', 'Ongoing'), ('Dropped', 'Dropped'), ('Completed', 'Completed')], default='Not Started', max_length=20)),
                ('priority', models.CharField(max_length=20)),
                ('deadline', models.DateField()),
                ('remarks', models.CharField(default='Task not started yet', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('update_history', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskUpdate',
        ),
    ]
