# Generated by Django 5.0.2 on 2024-03-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_remove_taskupdate_task_remove_taskupdate_user_tasks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='name',
            new_name='task_name',
        ),
    ]
